dist: xenial
#language: go

sudo: false

#go:
#  - master

git:
  depth: 1

install:
  - wget https://github.com/gohugoio/hugo/releases/download/v0.54.0/hugo_0.54.0_Linux-64bit.deb
  - sudo dpkg -i hugo*.deb
#  - go get github.com/gohugoio/hugo    # consume time 70.85s

before_script:
  - rm -rf public 2> /dev/null

script:
  - hugo -e production
#  - echo "$CNAME_URL" > public/CNAME

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  email: $GITHUB_EMAIL
  name: $GITHUB_USERNAME
  verbose: true
  keep-history: true
  local-dir: public
  target_branch: master  # branch contains blog content
  on:
    branch: master
