baseURL: "https://projekthilfe-uganda.de/"
languageCode: "de"
title: "Projekthilfe Uganda"
#theme: "phuganda"
#theme: "ananke"
watch: false
buildDrafts: false

outputs:
  page:
    - html
  home:
    - html
    - json
  section:
    - html
    - json

sitemap:
  changefreq: daily
  filename: sitemap.xml
  priority: 1.0

menu:
  main:
    - identifier: home
      pre: fa-home
      url: /
      weight: 10

    - identifier: verein
      name: Unser Verein
      url: /verein/
      weight: 20
    - parent: verein
      name: Kontakt
      url: /verein/kontakt
      weight: 10
    - parent: verein
      name: Hilfseinsätze vor Ort
      url: /verein/hilfseinsaetze
      weight: 20
    - parent: verein
      name: Verwaltungsstruktur Uganda
      url: /verein/verwaltungsstruktur-uganda
      weight: 30
    - parent: verein
      name: Bilder & Videos
      url: /verein/bilder-videos
      weight: 40
    - parent: verein
      name: Aktionen in Büchenau
      url: /verein/aktionen-buechenau
      weight: 50
    - parent: verein
      name: Hof-Trödel in Bengelshagen
      url: /verein/hof-troedel-bengelshagen
      weight: 60
    - parent: verein
      name: Auszeichnungen
      url: /verein/auszeichnungen
      weight: 70

    - identifier: projekte
      name: Unsere Projekte
      url: /projekte/
      weight: 30
    - parent: projekte
      name: Schulprojekte
      url: /projekte/schulprojekte
      weight: 10
    - parent: projekte
      name: Berufsausbildungen
      url: /projekte/berufsausbildungen
      weight: 20
    - parent: projekte
      name: Patenschaften
      url: /projekte/patenschaften
      weight: 30
    - parent: projekte
      name: Gesundheitsversorgung
      url: /projekte/gesundheitsversorgung
      weight: 40
    - parent: projekte
      name: Agrar-Hilfsprogramm für Kleinbauern
      url: /projekte/hilfsprogramm-kleinbauern
      weight: 50
    - parent: projekte
      name: Selbsthilfegruppen
      url: /projekte/selbsthilfegruppen
      weight: 60
    - parent: projekte
      name: Caritas für die Ärmsten
      url: /projekte/caritas
      weight: 70
#    - parent: projekte
#      name: Uganda Lebenshausstiftung
#      url: /projekte/uganda-lebenshaus-stiftung
#      weight: 80
    - parent: projekte
      name: Glockenturm
      url: /projekte/glockenturm
      weight: 90

    - identifier: helfen
      name: So können Sie helfen
      url: /helfen/
      weight: 40
    - parent: helfen
      name: Patenschaft
      url: /helfen/patenschaft
      weight: 10
    - parent: helfen
      name: Spendenshop
      url: /spenden
      weight: 20
    - parent: helfen
      name: Mitarbeit
      url: /helfen/mitarbeit
      weight: 30

    - identifier: news
      name: Aktuelles
      url: /news/
      weight: 50

#    - identifier: shop
#      name: Shop
#      url: /spenden/
#      weight: 60
