baseURL: "https://projekthilfe-uganda.de/"
languageCode: "de"
title: "Projekthilfe Uganda"
#theme: "phuganda"
#theme: "ananke"
watch: false
buildDrafts: false

menu:
  main:
    - identifier: home
      pre: fa-home
      url: /
      weight: 10

    - identifier: verein
      name: Unser Verein
      url: /verein/
      weight: 20
    - parent: verein
      name: Aktionen in Büchenau
      url: /verein/aktionen-buechenau
      weight: 10
    - parent: verein
      name: Auszeichnungen
      url: /verein/auszeichnungen
      weight: 20
    - parent: verein
      name: Bilder & Videos
      url: /verein/bilder-videos
      weight: 30
    - parent: verein
      name: Hilfseinsätze
      url: /verein/hilfseinsaetze
      weight: 40
    - parent: verein
      name: Hof-Trödel in Bengelshagen
      url: /verein/hof-troedel-bengelshagen
      weight: 50
    - parent: verein
      name: Kontakt
      url: /verein/kontakt
      weight: 60
    - parent: verein
      name: Verwaltungsstruktur Uganda
      url: /verein/verwaltungsstruktur-uganda
      weight: 70

    - identifier: projekte
      name: Unsere Projekte
      url: /projekte/
      weight: 30

    - identifier: helfen
      name: So können Sie helfen
      url: /helfen/
      weight: 40

    - identifier: news
      name: Aktuelles
      url: /news/
      weight: 50

    - identifier: shop
      name: Shop
      url: /shop/
      weight: 60
#  - identifier: menu
#    name: Menü
#    pre: fa-bars
#    weight: 50
