---
new_page_extension: md
auto_deploy: true
admin_path: "/admin"
webhook_url: 
sections:
- type: directory
  path: content
  label: Pages
  create: all
  match: "*"
- type: directory
  path: content/home
  label: Home
  create: documents
  match: "**/*"
  templates:
  - article
  - picture-teaser
  - carousel
  - article-with-picture
  - picture
- type: directory
  path: content/verein
  label: Unser Verein
  create: all
  match: "**/*"
  templates:
  - article
  - picture-teaser
  - carousel
  - article-with-picture
  - picture
- type: directory
  path: content/projekte
  label: Unsere Projekte
  create: all
  match: "**/*"
  templates:
  - article
  - picture-teaser
  - carousel
  - article-with-picture
  - picture
- type: directory
  path: content/helfen
  label: So können Sie Helfen
  create: documents
  match: "**/*"
  templates:
  - article
  - picture-teaser
  - carousel
  - article-with-picture
  - picture
- type: directory
  path: content/news
  label: Aktuelles
  create: documents
  match: "**/*"
  templates:
  - news
- type: directory
  path: content/shop/items
  label: Shop Items
  create: documents
  match: "*"
  templates:
  - shop-item
upload_dir: static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
instant_preview: 
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.53
  preview_output_directory: public
  preview_docker_image: forestryio/build:latest
  mount_path: "/opt/buildhome/repo"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
  publish_command: hugo -d public
  publish_env:
  - HUGO_ENV=production
  - HUGO_VERSION=0.53
  output_directory: public
  preview_command: hugo -E -F -D -b $DEPLOY_URL -d public
version: '0.53'
