---
label: article
hide_body: false
is_partial: false
fields:
- type: text
  name: type
  label: Type
  description: ''
  hidden: true
  default: article
- type: text
  label: Title
  name: title
  config:
    required: true
  default: ''
pages:
- content/verein/index.md
- content/helfen/mitarbeit.md
- content/verein/das-ist-ein-test.md
