---
label: article
hide_body: false
is_partial: false
fields:
- type: text
  name: type
  label: Type
  description: ''
  hidden: true
  default: article
- type: text
  label: Title
  name: title
  config:
    required: true
  default: ''
- type: datetime
  name: date
  label: Date
  description: Date of creation or last update.
  config:
    date_format: DD.MM.YYYY
pages:
- content/verein/index.md
- content/helfen/mitarbeit.md
- content/helfen/index.md
