---
label: project
hide_body: false
is_partial: false
fields:
- type: text
  name: type
  label: type
  hidden: true
  default: project
- type: text
  name: title
  label: Title
  config:
    required: true
- type: text
  name: date
  label: Date
